#include "nw_i0_tool"
/*   Script generated by
Lilac Soul's NWN Script Generator, v. 1.3

For download info, please visit:
http://www.lilacsoul.revility.com    */

int StartingConditional()
{
object oPC = GetPCSpeaker();

if (!AutoDC(DC_HARD, SKILL_PERSUADE, oPC)) return FALSE;

return TRUE;
}

